services:
  timetracker-backend:
    build:
      context: .
      dockerfile: ./compose/dev/timetracker/backend/Dockerfile
    image: timetracker-backend
    command: /start
    volumes:
      - .:/opt/timetracker
    env_file:
      - ./.env/.dev
    ports:
      - "8000:8000"
    depends_on:
      - timetracker-db
      - timetracker-redis-cache
      - timetracker-redis-session
    networks:
      - timetracker-network

  timetracker-db:
    image: postgres:14.4
    volumes:
      - timetracker_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env/.dev
    ports:
      - "5433:5432"
    networks:
      - timetracker-network
  timetracker-redis-cache:
    image: redis:7.0.4
    expose:
      - "6379"
    networks:
      - timetracker-network
  timetracker-redis-session:
    image: redis:7.0.4
    expose:
      - "6379"
    networks:
      - timetracker-network


volumes:
  timetracker_postgres_data:

networks:
  timetracker-network:
    external: true