# Generated by Django 5.0.4 on 2024-04-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="primary_contact",
        ),
        migrations.AddField(
            model_name="contact",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
