# Generated by Django 5.0.4 on 2024-04-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_remove_client_primary_contact_contact_is_primary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
