# Generated by Django 5.0.4 on 2024-04-25 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_timeentry_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeentry",
            name="duration",
        ),
    ]
